#:schema https://www.schemastore.org/treefmt.json

excludes = ["dist/**", "node_modules/**"]

[formatter.oxfmt]
command = "oxfmt"
options = ["--write"]
includes = ["*.js", "*.jsx", "*.ts", "*.tsx", "*.json", "*.yaml", "*.toml", "*.md"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]
