name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

# yaml-language-server-disable is not allowed
enable-openid-connect: true

jobs:
  action:
    # zizmor: ignore[excessive-permissions]
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run action
        uses: ./. # zizmor: ignore[unpinned-uses,self-repository]

  check:
    # zizmor: ignore[excessive-permissions]
    runs-on: ubuntu-26.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@65167e71611029bf1f64e4dd6492de35ab553ae2 # v1.66.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          niks3_url: https://niks3.trev.zip

      - name: Check
        run: nix flake check
